### ISSUE TITLE
Yocto bitbake cannot compile pion/dtls/v2

### ISSUE THREAD

**Issue by rtechencheng** [pion/dtls#385]
### Your environment.
  - Version: *v2.0.9*
  - Browser: *N/A*
  - Other Information - Detail description under here https://github.com/rtechencheng/pion-dtls-yocto-integrate

### What did you do?

See https://github.com/rtechencheng/pion-dtls-yocto-integrate

### What did you expect?
To be able to `bitbake` pion/dtls/v2.

### What happened?
Compilation error.

**Comment by daenney** [comment]
This does not provide remotely enough information for us to do anything. The output from the compilation attempts are missing too.

If you can provide additional info, we might be able to help. But as long as things `go build` using the regular Go toolchain this'll largely be a "won't fix" kind of issue for us.

**Comment by rtechencheng** [comment]
> This does not provide remotely enough information for us to do anything. The output from the compilation attempts are missing too.
> 
> If you can provide additional info, we might be able to help. But as long as things `go build` using the regular Go toolchain this'll largely be a "won't fix" kind of issue for us.

I understand you point. And your dtls library is really nice so that is why I want to try on Yocto.
But it is hard to provide the exact information that you want, cause Yocto builds the go cross compiler from the source before compiling any other go packages. So it's beyond just using `go build` on a host machine.
But first of all, is there any requirement regarding the `go` toolchain version to be able to compile your library?

**Comment by daenney** [comment]
There's no special requirements.

After a whole bunch of spelunking, I found this: https://github.com/rtechencheng/pion-dtls-yocto-integrate/blob/main/build/github.com-pion-dtls-v2/2.0.9-r0/temp/log.do_compile.1112306 (providing that output directly would've been helpful).

It seems that you're using an aarch64 toolchain but it's looking for the amd64 go linker. That's not right. It looks like you're trying to cross-compile things? Are you passing through `OOS=linux GOARCH=arm64` when building?

**Comment by rtechencheng** [comment]
Yes! you are exactly hitting the point! Great eyes.
But yes, `OOS=linux GOARCH=arm64` if you check https://github.com/rtechencheng/pion-dtls-yocto-integrate/blob/main/build/github.com-pion-dtls-v2/2.0.9-r0/temp/run.do_compile.1112306

**Comment by rtechencheng** [comment]
One thing I don't understand is that in the error log, the cross-compiler is trying to find asn1 native/host (x86) package from the pseudo sysroot (recipe-sysroot-native) but I only have the asn1 package installed in target (arm64) sysroot (recipe-sysroot). I am not familiar with this `importcfg` thing, how does it work in a go compiler?

**Comment by daenney** [comment]
`importcfg` is an option to `go tool compile: https://pkg.go.dev/cmd/compile. I have no idea what would be calling that though.

**Comment by Sean-Der** [comment]
@rtechencheng I am not familiar with Yocto, are you able to compile a minimal hello world with this setup? Is pion/dtls causing the issue, or one of our dependencies?

Just something like this in `main.go`

```
package main

import "fmt"

func main() {
    fmt.Println("vim-go")
}
```

**Comment by rtechencheng** [comment]
I have no problem compiling a hello world.
And I am able to compile all the libraries I linked in my repo:
https://github.com/rtechencheng/pion-dtls-yocto-integrate#version-info

The only thing that is not compiling is the examples in your repo. If I remove the example source code manually right before Yocto bitbake starts compiling it, then your library compiles fine.

**Comment by daenney** [comment]
Can we narrow it down to a particular example? Looking at them, I can't really see anything that should trip things up.

**Comment by rtechencheng** [comment]
Looks like to me are the `dial` and `listen` examples.

**Comment by Sean-Der** [comment]
@rtechencheng is it an issue if you have multiple definitions of main, did dial+listen fail when compiled on their own as well? Can you try just compiling `examples/dial/verify` ?

**Comment by rtechencheng** [comment]
No single example, e.g. `examples/dial/verify`, does not compile:
```
DEBUG: Executing python function remove_testdirs
DEBUG: Python function remove_testdirs finished
DEBUG: Executing python function create_pseudo_mod
DEBUG: Python function create_pseudo_mod finished
DEBUG: Executing shell function do_compile
internal/cpu
runtime/internal/atomic
runtime/internal/sys
internal/race
sync/atomic
runtime/internal/math
internal/bytealg
unicode
unicode/utf8
container/list
math/bits
crypto/internal/subtle
crypto/subtle
internal/testlog
math
unicode/utf16
vendor/golang.org/x/crypto/cryptobyte/asn1
internal/nettrace
runtime/cgo
runtime
vendor/golang.org/x/crypto/internal/subtle
encoding
github.com/pion/dtls/v2/pkg/crypto/clientcertificate
github.com/pion/dtls/v2/pkg/crypto/signature
internal/reflectlite
sync
internal/singleflight
math/rand
errors
sort
internal/oserror
io
strconv
syscall
vendor/golang.org/x/net/dns/dnsmessage
bytes
hash
crypto
reflect
strings
crypto/internal/randutil
bufio
crypto/hmac
crypto/rc4
vendor/golang.org/x/crypto/hkdf
time
internal/syscall/unix
internal/syscall/execenv
context
internal/poll
github.com/pion/dtls/v2/internal/closer
os
internal/fmtsort
encoding/binary
crypto/sha512
crypto/cipher
crypto/ed25519/internal/edwards25519
fmt
crypto/md5
crypto/aes
crypto/des
crypto/sha1
crypto/sha256
encoding/base64
path/filepath
encoding/pem
net
io/ioutil
encoding/hex
math/big
net/url
vendor/golang.org/x/crypto/chacha20
vendor/golang.org/x/crypto/poly1305
vendor/golang.org/x/crypto/curve25519
vendor/golang.org/x/crypto/chacha20poly1305
encoding/gob
github.com/pion/dtls/v2/internal/util
github.com/pion/dtls/v2/pkg/crypto/ccm
golang.org/x/crypto/curve25519/internal/field
github.com/pion/dtls/v2/pkg/crypto/hash
log
encoding/asn1
crypto/elliptic
crypto/rand
crypto/ed25519
crypto/rsa
crypto/dsa
crypto/ecdsa
crypto/x509/pkix
vendor/golang.org/x/crypto/cryptobyte
github.com/pion/dtls/v2/pkg/crypto/elliptic
golang.org/x/crypto/cryptobyte
github.com/pion/dtls/v2/pkg/protocol
github.com/pion/transport/connctx
github.com/pion/udp
crypto/x509
github.com/pion/dtls/v2/pkg/crypto/prf
github.com/pion/dtls/v2/pkg/protocol/alert
crypto/tls
github.com/pion/dtls/v2/pkg/crypto/signaturehash
github.com/pion/dtls/v2/examples/util
github.com/pion/dtls/v2/pkg/protocol/extension
github.com/pion/dtls/v2/pkg/protocol/handshake
github.com/pion/dtls/v2/pkg/protocol/recordlayer
github.com/pion/dtls/v2/pkg/crypto/ciphersuite
github.com/pion/dtls/v2/internal/ciphersuite
github.com/pion/dtls/v2
github.com/pion/dtls/v2/examples/dial/verify
# github.com/pion/dtls/v2/examples/dial/verify
cannot find package golang.org/x/crypto/cryptobyte/asn1 (using -importcfg)
/home/chencheng/workspace/wittra/repos/wittra-gateway/yocto/build/tmp-glibc/work/aarch64-wittra-linux/github.com-pion-dtls-v2-example-dial-verify/2.0.9-r0/recipe-sysroot-native/usr/lib/aarch64-wittra-linux/go/pkg/tool/linux_amd64/link: cannot open file : open : no such file or directory
WARNING: exit code 2 from a shell command.
ERROR: Execution of '/home/chencheng/workspace/wittra/repos/wittra-gateway/yocto/build/tmp-glibc/work/aarch64-wittra-linux/github.com-pion-dtls-v2-example-dial-verify/2.0.9-r0/temp/run.do_compile.3746420' failed with exit code 2:
internal/cpu
runtime/internal/atomic
runtime/internal/sys
internal/race
sync/atomic
runtime/internal/math
internal/bytealg
unicode
unicode/utf8
container/list
math/bits
crypto/internal/subtle
crypto/subtle
internal/testlog
math
unicode/utf16
vendor/golang.org/x/crypto/cryptobyte/asn1
internal/nettrace
runtime/cgo
runtime
vendor/golang.org/x/crypto/internal/subtle
encoding
github.com/pion/dtls/v2/pkg/crypto/clientcertificate
github.com/pion/dtls/v2/pkg/crypto/signature
internal/reflectlite
sync
internal/singleflight
math/rand
errors
sort
internal/oserror
io
strconv
syscall
vendor/golang.org/x/net/dns/dnsmessage
bytes
hash
crypto
reflect
strings
crypto/internal/randutil
bufio
crypto/hmac
crypto/rc4
vendor/golang.org/x/crypto/hkdf
time
internal/syscall/unix
internal/syscall/execenv
context
internal/poll
github.com/pion/dtls/v2/internal/closer
os
internal/fmtsort
encoding/binary
crypto/sha512
crypto/cipher
crypto/ed25519/internal/edwards25519
fmt
crypto/md5
crypto/aes
crypto/des
crypto/sha1
crypto/sha256
encoding/base64
path/filepath
encoding/pem
net
io/ioutil
encoding/hex
math/big
net/url
vendor/golang.org/x/crypto/chacha20
vendor/golang.org/x/crypto/poly1305
vendor/golang.org/x/crypto/curve25519
vendor/golang.org/x/crypto/chacha20poly1305
encoding/gob
github.com/pion/dtls/v2/internal/util
github.com/pion/dtls/v2/pkg/crypto/ccm
golang.org/x/crypto/curve25519/internal/field
github.com/pion/dtls/v2/pkg/crypto/hash
log
encoding/asn1
crypto/elliptic
crypto/rand
crypto/ed25519
crypto/rsa
crypto/dsa
crypto/ecdsa
crypto/x509/pkix
vendor/golang.org/x/crypto/cryptobyte
github.com/pion/dtls/v2/pkg/crypto/elliptic
golang.org/x/crypto/cryptobyte
github.com/pion/dtls/v2/pkg/protocol
github.com/pion/transport/connctx
github.com/pion/udp
crypto/x509
github.com/pion/dtls/v2/pkg/crypto/prf
github.com/pion/dtls/v2/pkg/protocol/alert
crypto/tls
github.com/pion/dtls/v2/pkg/crypto/signaturehash
github.com/pion/dtls/v2/examples/util
github.com/pion/dtls/v2/pkg/protocol/extension
github.com/pion/dtls/v2/pkg/protocol/handshake
github.com/pion/dtls/v2/pkg/protocol/recordlayer
github.com/pion/dtls/v2/pkg/crypto/ciphersuite
github.com/pion/dtls/v2/internal/ciphersuite
github.com/pion/dtls/v2
github.com/pion/dtls/v2/examples/dial/verify
# github.com/pion/dtls/v2/examples/dial/verify
cannot find package golang.org/x/crypto/cryptobyte/asn1 (using -importcfg)
/home/chencheng/workspace/wittra/repos/wittra-gateway/yocto/build/tmp-glibc/work/aarch64-wittra-linux/github.com-pion-dtls-v2-example-dial-verify/2.0.9-r0/recipe-sysroot-native/usr/lib/aarch64-wittra-linux/go/pkg/tool/linux_amd64/link: cannot open file : open : no such file or directory
WARNING: exit code 2 from a shell command.
```

**Comment by rtechencheng** [comment]
I guess it is not an issue with your example code. But something related to Yocto generated go compiler.
Not sure if it is related to this one:
https://www.programmersought.com/article/64993527313/

**Comment by rtechencheng** [comment]
I think I will close this for now cause putting all the source code of all the recursive dependency packages in the same workspace will help to compile it. It must be something in Yocto environment.
